default: &default
  host: <%= ENV['MICRO_ADS_DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['MICRO_ADS_DATABASE_USER'] || 'micro_ads' %>
  password: <%= ENV['MICRO_ADS_DATABASE_USER_PASSWORD'] %>
  port: <%= ENV['MICRO_ADS_DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: micro_ads_development

test:
  <<: *default
  database: micro_ads_test

production:
  <<: *default
  database: micro_ads_production
