app:
  name: ads
  schema_file_name: 'schema.rb'
  seed_folder_path: <%= "#{RootPath::PATH}/db/seeds" %>
  migrations_folder_path: <%= "#{RootPath::PATH}/db/migrations" %>
  db_schema_folder_path: <%= "#{RootPath::PATH}/db" %>
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD']%>
  consumer_pool: 10
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: password
  port: 5432
  url: <%= ENV['ADS_DATABASE_URL'] %>
pagination:
  page_size: 10
api_endpoints:
  auth_link:
  geocoder_link:
logger:
  path: log/app.log
  level: info
